project: "量潮数字资产管理标准"
copyright: "2026"
author: "量潮科技"

launch_buttons:
  colab: null
  jupyterhub: null
  binder: "https://mybinder.org/v2/gh/quanttide/quanttide-specification-of-asset-management/main"

repository:
  url: "https://github.com/quanttide/quanttide-specification-of-asset-management"
  branch: "main"

exclude_patterns:
  - "_build"
  - "Thumbs.db"
  - ".DS_Store"

html_theme: "sphinx_book_theme"
html_title: "量潮数字资产管理标准"
html_short_title: "规范"
